# Generated by Django 3.1.7 on 2021-02-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id_students', models.IntegerField(db_column='id_Students', primary_key=True, serialize=False)),
                ('name_students', models.CharField(blank=True, db_column='name_Students', max_length=45, null=True)),
                ('passwords', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
    ]
