# Generated by Django 3.1.7 on 2021-03-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id_projects', models.AutoField(db_column='id_Projects', primary_key=True, serialize=False)),
                ('name_projects', models.CharField(blank=True, db_column='title_projects', max_length=45, null=True)),
                ('filled_projects', models.CharField(blank=True, max_length=45, null=True)),
                ('descriotion_projects', models.CharField(blank=True, max_length=45, null=True)),
                ('file_project', models.FileField(blank=True, db_column='File_Project', null=True, upload_to='doucment')),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
    ]
