# Generated by Django 3.1.7 on 2021-03-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id_projects', models.IntegerField(db_column='id_Projects', default='', primary_key=True, serialize=False)),
                ('name_projects', models.CharField(blank=True, max_length=45, null=True)),
                ('filled_projects', models.CharField(blank=True, max_length=45, null=True)),
                ('descriotion_projects', models.CharField(blank=True, max_length=45, null=True)),
                ('name_doctor', models.CharField(blank=True, max_length=45, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='documents')),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
    ]
