# Generated by Django 3.1.6 on 2021-02-20 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteesCharis',
            fields=[
                ('id_committees_charis', models.IntegerField(primary_key=True, serialize=False)),
                ('name_committees_charis', models.CharField(blank=True, max_length=45, null=True)),
                ('passwords', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'committees_charis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id_department', models.IntegerField(primary_key=True, serialize=False)),
                ('name_department', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id_doctors', models.IntegerField(db_column='id_Doctors', primary_key=True, serialize=False)),
                ('name_doctors', models.CharField(blank=True, db_column='name_Doctors', max_length=45, null=True)),
                ('passwords', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'doctors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id_evaluation', models.IntegerField(db_column='id_Evaluation', primary_key=True, serialize=False)),
                ('gread_evaluation', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'evaluation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Examiners',
            fields=[
                ('id_examiners', models.IntegerField(db_column='id_Examiners', primary_key=True, serialize=False)),
                ('name_examiners', models.CharField(blank=True, db_column='name_Examiners', max_length=45, null=True)),
            ],
            options={
                'db_table': 'examiners',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id_groups', models.IntegerField(primary_key=True, serialize=False)),
                ('name_groups', models.CharField(blank=True, db_column='name_Groups', max_length=45, null=True)),
                ('idea_groups', models.CharField(blank=True, db_column='idea_Groups', max_length=45, null=True)),
                ('idea_fescription', models.CharField(blank=True, max_length=45, null=True)),
                ('idea_speciallty', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': '_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id_projects', models.IntegerField(db_column='id_Projects', primary_key=True, serialize=False)),
                ('name_projects', models.CharField(blank=True, max_length=45, null=True)),
                ('filled_projects', models.CharField(blank=True, max_length=45, null=True)),
                ('descriotion_projects', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id_students', models.OneToOneField(db_column='id_Students', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='committeeChairs.department')),
                ('name_students', models.CharField(blank=True, db_column='name_Students', max_length=45, null=True)),
                ('passwords', models.CharField(blank=True, max_length=45, null=True)),
                ('id_department_fk', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
    ]
