# Generated by Django 3.1.7 on 2021-02-20 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committeeChairs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctors',
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
        migrations.DeleteModel(
            name='Examiners',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.RemoveField(
            model_name='students',
            name='id_students',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
