# Generated by Django 3.1.7 on 2021-03-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examiners',
            fields=[
                ('id_examiners', models.AutoField(db_column='id_Examiners', primary_key=True, serialize=False)),
                ('name_examiners', models.CharField(blank=True, db_column='name_Examiners', max_length=45, null=True)),
            ],
            options={
                'db_table': 'examiners',
                'managed': False,
            },
        ),
    ]
