# Generated by Django 3.1.7 on 2021-03-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id_groups', models.AutoField(primary_key=True, serialize=False)),
                ('name_groups', models.CharField(blank=True, db_column='name_Groups', max_length=45, null=True)),
            ],
            options={
                'db_table': '_groups',
                'managed': False,
            },
        ),
    ]
