# Generated by Django 3.1.7 on 2021-03-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id_department', models.AutoField(primary_key=True, serialize=False)),
                ('name_department', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
    ]
